package main

const pageHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>WireGuard ACL Manager</title>
<style>
:root{font:15px/1.5 system-ui,sans-serif;color:#202827;background:#f5f6f4}*{box-sizing:border-box}body{margin:0}header{background:#152f2a;color:white;padding:1.2rem max(1rem,calc((100vw - 1180px)/2))}header h1{font-size:1.35rem;margin:0}header p{margin:.2rem 0 0;color:#bbd3cb}main{max-width:1180px;margin:auto;padding:1.5rem 1rem 4rem}nav{display:flex;gap:.8rem;flex-wrap:wrap;margin-bottom:1.2rem}nav a{color:#19554a;text-decoration:none;font-weight:650}section{background:white;border:1px solid #d9dfdc;border-radius:8px;padding:1.1rem;margin-bottom:1.2rem;box-shadow:0 1px 2px #0000000d}h2{font-size:1.15rem;margin:0 0 .8rem}h3{font-size:1rem;margin:.5rem 0}p{margin:.5rem 0}table{border-collapse:collapse;width:100%}th,td{text-align:left;padding:.55rem;border-bottom:1px solid #e6ebe8;vertical-align:top}th{font-size:.8rem;text-transform:uppercase;letter-spacing:.03em;color:#53635d}code{overflow-wrap:anywhere}.scroll{overflow-x:auto}form{display:flex;gap:.55rem;align-items:end;flex-wrap:wrap;margin:.6rem 0}label{display:grid;gap:.2rem;font-size:.85rem;font-weight:600}input,select,button{font:inherit;padding:.4rem .5rem;border:1px solid #bac8c1;border-radius:4px;background:white;color:#202827}input[type=checkbox]{width:1rem;height:1rem}button{background:#225d4e;color:white;border-color:#225d4e;cursor:pointer;font-weight:600}button.secondary{background:white;color:#225d4e}button.danger{background:#8b2f2f;border-color:#8b2f2f}button:hover{filter:brightness(.92)}.muted{color:#63716a}.badge{padding:.15rem .45rem;border-radius:4px;font-weight:700;font-size:.8rem;background:#e7eee9}.ALLOW,.IN_SYNC{color:#166342;background:#e5f5eb}.DENY,.ERROR{color:#a22d2d;background:#f9e7e7}.OUT_OF_SYNC{color:#855a05;background:#fff2d6}.UNMANAGED,.INACTIVE{color:#626969;background:#eceeee}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.8rem}.metric{background:#f5f8f6;border:1px solid #e2e9e4;padding:.7rem;border-radius:5px}.metric strong{display:block;font-size:1.05rem}details{margin:.3rem 0}summary{cursor:pointer;color:#205e50}small{color:#65736d}.notice{background:#fff5dc;padding:.75rem;border-left:3px solid #bc8c22}
</style></head><body><header><h1>WireGuard ACL Manager</h1><p>Access from VPN peers to registered internal resources</p></header>
<main><nav><a href="#status">Status</a><a href="#peers">Peers</a><a href="#groups">Groups</a><a href="#resources">Resources</a><a href="#policies">Policies</a><a href="/api/diagnostics">Diagnostics JSON</a><a href="/api/audit">Audit JSON</a></nav>
<section id="status"><h2>Enforcement status</h2><div class="grid">
<div class="metric">State<strong><span class="badge {{.S.State}}">{{.S.State}}</span></strong></div>
<div class="metric">Desired revision<strong>{{.V.Desired.Revision}}</strong></div>
<div class="metric">Applied revision<strong>{{.S.AppliedRevision}}</strong></div>
<div class="metric">Last successful apply<strong>{{if .S.LastSuccess}}{{.S.LastSuccess}}{{else}}Never{{end}}</strong></div>
</div>
{{if .S.LastError}}<p class="notice"><strong>Last error:</strong> {{.S.LastError}}</p>{{end}}
<p><small>Active chain: {{if .S.Chain}}{{.S.Chain}}{{else}}none{{end}} · anchor present: {{.S.AnchorPresent}} · before wg-easy ACCEPT: {{.S.AnchorBeforeAccept}} · last attempt: {{.S.LastAttempt}}</small></p>
<p>Peer sync: <span class="badge {{if eq .Sync.State "OK"}}IN_SYNC{{else if eq .Sync.State "ERROR"}}ERROR{{else}}INACTIVE{{end}}">{{.Sync.State}}</span> <small>{{.Sync.At}}</small>{{if .Sync.Error}} · {{.Sync.Error}}{{end}}</p>
<form method="post" action="/retry"><input type="hidden" name="csrf" value="{{.CSRF}}"><button class="secondary">Reconcile / retry</button></form>
{{if not .V.Desired.Activated}}<p class="notice">Installation is passive. Review synchronized peers, resources, and policies before activating. Registered resources will then default to DENY.</p>
<form method="post" action="/activate"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Type ACTIVATE<input name="confirm" required autocomplete="off"></label><button>Activate enforcement</button></form>{{end}}
</section>
<section id="peers"><h2>Peers</h2><p class="muted">wg-easy owns peer identity and addresses. Missing peers stay reserved and cannot be reassigned silently.</p>
<form method="post" action="/sync"><input type="hidden" name="csrf" value="{{.CSRF}}"><button>Synchronize from wg-easy</button></form>
<div class="scroll"><table><thead><tr><th>Name</th><th>VPN IPv4</th><th>Public key</th><th>Groups</th><th>Effective access</th><th>Sync</th></tr></thead><tbody>
{{range .V.Peers}}<tr><td>{{if .Name}}{{.Name}}{{else}}<span class="muted">Unnamed peer</span>{{end}}</td><td><code>{{.IP}}</code></td><td><details><summary><code>{{short .PublicKey}}</code></summary><code>{{.PublicKey}}</code></details></td>
<td>{{range .Groups}}<span class="badge">{{group $.V.Groups .}}</span> {{else}}—{{end}}</td>
<td>{{with index $.Access .ID}}{{range .}}<span class="badge ALLOW">{{.}}</span> {{end}}{{else}}<span class="muted">No grants</span>{{end}}</td>
<td><span class="badge {{if eq .SyncStatus "present"}}IN_SYNC{{else}}ERROR{{end}}">{{.SyncStatus}}</span>{{if not .Enabled}} disabled{{end}}<br><small>{{.LastSeen}}</small>
<details><summary>Forget ACL record</summary><small>Removes this peer's ACL policies and memberships. wg-easy peer is unchanged. Sync imports it later with default DENY.</small><form method="post" action="/peers/forget"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><label>Type peer ID {{.ExternalID}}<input name="confirm" required autocomplete="off"></label><button class="danger">Forget</button></form></details></td></tr>{{else}}<tr><td colspan="6">No peers synchronized yet.</td></tr>{{end}}
</tbody></table></div></section>
<section id="groups"><h2>Groups and membership</h2>
<form method="post" action="/groups/save"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>New group name<input name="name" maxlength="120" required></label><button>Create group</button></form>
{{range .V.Groups}}<details><summary><strong>{{.Name}}</strong> · {{len .Members}} members</summary>
<form method="post" action="/groups/save"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><label>Name<input name="name" value="{{.Name}}" maxlength="120" required></label><button class="secondary">Rename</button></form>
<form method="post" action="/groups/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><button class="danger">Delete group</button></form>
<p>Members: {{range .Members}}{{peer $.V.Peers .}} · {{else}}none{{end}}</p></details>{{end}}
{{if and .V.Groups .V.Peers}}<h3>Change membership</h3><form method="post" action="/membership"><input type="hidden" name="csrf" value="{{.CSRF}}">
<label>Peer<select name="peer_id">{{range .V.Peers}}<option value="{{.ID}}">{{.Name}} ({{.IP}})</option>{{end}}</select></label>
<label>Group<select name="group_id">{{range .V.Groups}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label>
<label>Action<select name="action"><option value="add">Add</option><option value="remove">Remove</option></select></label><button>Save membership</button></form>{{end}}
</section>
<section id="resources"><h2>Registered resources</h2><p class="muted">Disabled resources are unmanaged: their traffic returns to wg-easy forwarding.</p>
<form method="post" action="/resources/save"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Name<input name="name" required maxlength="120"></label><label>Description<input name="description"></label><label>Destination CIDR<input name="destination" placeholder="172.20.57.245/32" required></label><label>Protocol<select name="protocol"><option>tcp</option><option>udp</option><option>icmp</option><option>any</option></select></label><label>Port or range<input name="port" placeholder="3306 or 8000-8010"></label><label>Enabled<input type="checkbox" name="enabled" checked></label><button>Add resource</button></form>
{{range .V.Resources}}<details><summary>{{.Name}} · <code>{{.Destination}}</code> · {{.Protocol}}/{{port .}} · {{if .Enabled}}enabled{{else}}disabled{{end}}</summary>
<p>{{.Description}}</p><form method="post" action="/resources/save"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><label>Name<input name="name" value="{{.Name}}" required></label><label>Description<input name="description" value="{{.Description}}"></label><label>Destination CIDR<input name="destination" value="{{.Destination}}" required></label><label>Protocol<select name="protocol"><option value="tcp" {{if eq .Protocol "tcp"}}selected{{end}}>tcp</option><option value="udp" {{if eq .Protocol "udp"}}selected{{end}}>udp</option><option value="icmp" {{if eq .Protocol "icmp"}}selected{{end}}>icmp</option><option value="any" {{if eq .Protocol "any"}}selected{{end}}>any</option></select></label><label>Port or range<input name="port" value="{{if .PortStart}}{{.PortStart}}{{if ne .PortStart .PortEnd}}-{{.PortEnd}}{{end}}{{end}}"></label><label>Enabled<input type="checkbox" name="enabled" {{if .Enabled}}checked{{end}}></label><button class="secondary">Save</button></form>
<form method="post" action="/resources/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><button class="danger">Delete resource</button></form></details>{{else}}<p>No registered resources.</p>{{end}}
</section>
<section id="policies"><h2>Policies</h2><p class="muted">DENY overrides ALLOW across direct and group policies. No policy means default DENY for an enabled resource.</p>
{{if .V.Resources}}<h3>Set policy</h3><form method="post" action="/policies/save"><input type="hidden" name="csrf" value="{{.CSRF}}"><label>Peer (leave blank for group)<select name="peer_id"><option value="0">—</option>{{range .V.Peers}}<option value="{{.ID}}">{{.Name}} ({{.IP}})</option>{{end}}</select></label><label>Group (leave blank for peer)<select name="group_id"><option value="0">—</option>{{range .V.Groups}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Resource<select name="resource_id">{{range .V.Resources}}<option value="{{.ID}}">{{.Name}}</option>{{end}}</select></label><label>Action<select name="action"><option>ALLOW</option><option>DENY</option></select></label><button>Save policy</button></form>{{end}}
<h3>Explicit policies</h3><div class="scroll"><table><thead><tr><th>Subject</th><th>Resource</th><th>Action</th><th></th></tr></thead><tbody>{{range .V.Policies}}<tr><td>{{if .PeerID}}Peer: {{peer $.V.Peers .PeerID}}{{else}}Group: {{group $.V.Groups .GroupID}}{{end}}</td><td>{{res $.V.Resources .ResourceID}}</td><td><span class="badge {{.Action}}">{{.Action}}</span></td><td><form method="post" action="/policies/delete"><input type="hidden" name="csrf" value="{{$.CSRF}}"><input type="hidden" name="id" value="{{.ID}}"><button class="danger">Remove</button></form></td></tr>{{else}}<tr><td colspan="4">No explicit policies.</td></tr>{{end}}</tbody></table></div>
<h3>Effective peer access and reason</h3><div class="scroll"><table><thead><tr><th>Peer</th><th>Resource</th><th>Result</th><th>Why</th></tr></thead><tbody>{{range .Rows}}<tr><td>{{.Peer.Name}} ({{.Peer.IP}})</td><td>{{.Resource.Name}}</td><td><span class="badge {{.Cell.Result}}">{{.Cell.Result}}</span></td><td>{{.Cell.Reason}}</td></tr>{{else}}<tr><td colspan="4">Synchronize peers and register resources to see effective access.</td></tr>{{end}}</tbody></table></div>
</section></main></body></html>`
